notes/urls.py
from django.conf.urls import patterns, include, url
from notes_application import views 

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url('^$', views.show_start_page, name = "main"),
    url('^login/$', views.show_login_page, name = "login"),
    url('^logout/$', views.logout, name = "logout"),
    url(r'', include('social_auth.urls')),
    url('^notes_list/$', views.notes_list, name = "notes_list"),
    url('^add_email/$', views.add_email, name = "add_email"),
    url('^check_email/$', views.check_email, name = "check_email"),
    url('^confirm/([A-Za-z0-9]{,33})$', views.confirm_email, name = "confirm"),
    url('^email_auto_compl/$', views.email_auto_compl, name = "email_auto_compl"),

    url('^notes_lists/$', views.notes_lists, name = "notes_lists"),

    url('^note_content/([0-9]+)/ajax$', views.note_content, name = "note_content"),
    url('^note_content/$', views.note_content, name = "note_content"),
    url('^note_content/([0-9]+)$', views.notes_list, name = "note_content"),

    url('^delete_note/([0-9]+)$', views.delete_note, name = "delete_note"),
    url('^delete_note/$', views.delete_note, name = "delete_note"),

    url('^save_note/$', views.save_note, name = "save_note"),
    url('^save_note/([0-9]+)$', views.save_note, name = "save_note"),

    url('^edit_note/([0-9]+)$', views.edit_note, name = "edit_note"),
    url('^edit_note/$', views.edit_note, name = "edit_note"),

    url('^notes_menu/([0-9]+)$', views.notes_menu, name = "notes_menu"),
    url('^notes_menu/$', views.notes_menu, name = "notes_menu"),

    url('^notes_menu/(?P<sort>date|importance|shared)$', views.notes_menu, name = "notes_menu"),
    # Examples:
    # url(r'^$', 'notes.views.home', name='home'),
    # url(r'^notes/', include('notes.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

notes/notes_application/models.py
from django.db import models
from django.contrib.auth.models import User

class Notes (models.Model):
    title = models.CharField(max_length=1000)
    text = models.TextField()
    owner = models.ForeignKey(User)
    date_created = models.DateTimeField(auto_now_add = True)
    last_edit = models.DateTimeField(auto_now = True)
    shared_to = models.ManyToManyField(User, blank=True, null=True, related_name="shared")
    importance = models.TextField (choices = (
                    (u'Low', u'Low'),
                    (u'Normal', u'Normal'),
                    (u'High', u'High'),
                    (u'Very High', u'Very High'),
    ))

    def __unicode__(self):
        return '%s -- %s' % (self.owner, self.title)


class ConfirmEmail (models.Model):
    user = models.ForeignKey(User)
    date_created = models.DateTimeField(auto_now_add = True)
    confirm_code = models.CharField(max_length=33)
    email = models.EmailField(blank = True)

notes/notes_application/forms.py
from django import forms

class NoteForm(forms.Form):
    title = forms.CharField(required=False)
    text = forms.CharField(widget=forms.HiddenInput(), required=False)
    OPTIONS = (
                    ('', 'Priority'),
                    (u'Low', 'Low'),
                    (u'Normal', 'Normal'),
                    (u'High', 'High'),
                    (u'Very High', 'Very High'),
                )
    importance = forms.ChoiceField(widget=forms.Select, choices=OPTIONS, required=False)
    shared_to = forms.CharField(required=False)


class AddEmailForm(forms.Form):
    email = forms.EmailField()

notes/notes_application/views.py
# Create your views here.
from forms import *
from django.template import RequestContext
from django.contrib import auth
from django.contrib.auth.models import User
from django.shortcuts import render_to_response
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.mail import send_mail
from models import Notes, ConfirmEmail 
from django.utils.timezone import utc
import string, random, datetime, json

def user_with_email(user):
    if user.email:
        return True
    else:
        return False

def show_start_page(request):
    if request.user.is_authenticated():
        username = request.user.first_name + " " + request.user.last_name
        if username == " ":
            username = request.user.username
        return render_to_response('index.html', {'user': username})
    else:
        return render_to_response('index.html', {'user': "Anonymous"})

def show_login_page(request):
    return render_to_response('login.html', {})

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect("/")

def check_email(request):
    """
        View for redirecting users, which just has been logined.
    """
    if request.user.email:
        return HttpResponseRedirect('/notes_list/')
    else:
        return HttpResponseRedirect('/add_email/')

@login_required
def add_email(request):
    """
        Show add email page for GET request. Send email confirmation for POST request.
    """
    if request.method == 'GET':
        form = AddEmailForm
        return render_to_response('add_email.html', {'form': form}, context_instance=RequestContext(request))
    if request.method == 'POST':
        form = AddEmailForm(request.POST)
        if form.is_valid():
            clean_data = form.cleaned_data
            confirmation_code = ''.join(random.choice(string.ascii_uppercase + string.digits + string.ascii_lowercase) for x in range(33))
            content = "http://semenov.ipq.co/confirm/" + confirmation_code
            send_mail(
                "Confirm registration",
                content,
                'notes.noreplay@gmail.com',
                [clean_data.get('email', 'noreply@example.com')],
                fail_silently=False
            )
            ConfirmEmail.objects.filter(user = request.user).delete()
            confirmation = ConfirmEmail(user = request.user, confirm_code = confirmation_code, email = clean_data['email']) 
            confirmation.save()
            return HttpResponseRedirect('/')
        return render_to_response('add_email.html', {'form': form}, context_instance=RequestContext(request))

def confirm_email(request, email_code):
    """
        This view calling, when user confirm email. If success email adding.
    """
    try:
        confirmation = ConfirmEmail.objects.get(confirm_code = email_code) 
    except:
        raise Http404
    if confirmation.date_created > (datetime.datetime.utcnow().replace(tzinfo=utc) - datetime.timedelta(days=1)):
        user = confirmation.user
        user.email = confirmation.email
        user.save()
        confirmation.delete()
    return HttpResponseRedirect('/notes_list/')

def email_auto_compl(request):
    """
        Responce for email autocomplite input field.
    """
    response_data = {}
    response_data['suggestions'] = []
    if 'query' in request.GET and request.GET['query']:
        response_data['query'] = request.GET['query']
        try:
            users = User.objects.filter(email__icontains = request.GET['query'])
            for user in users:
                response_data['suggestions'].append(user.email)
        except:
            pass
        print response_data
    return HttpResponse(json.dumps(response_data), content_type="application/json")

@login_required
@user_passes_test(user_with_email, login_url="/add_email/")
def edit_note(request, note_id=None):
    """
        View for adding or editing note.
    """
    if note_id:
        try:
            note = Notes.objects.get(owner = request.user, id = note_id)
            title = note.title
            text = note.text
            importance  = note.importance
            shared_to = ""
        except:
            title = ""
            text = ""
        form = NoteForm(
                initial={'title': title, 'text': text, 'importance': importance, 'shared_to': shared_to}
        )
        return render_to_response('edit_note.html', {'form': form, 'note_id': note_id}, context_instance=RequestContext(request))
    else:
        form = NoteForm()
        return render_to_response('edit_note.html', {'form': form}, context_instance=RequestContext(request))

@login_required
@user_passes_test(user_with_email, login_url="/add_email/")
def notes_menu(request, note_id = None, sort=None):
    """
        Returns content for notes_lists page. Loading by AJAX.
    """
    assert request.method == 'GET'
    if sort == "date":
        user_notes = Notes.objects.filter(owner = request.user).order_by("-last_edit")
    elif sort == "importance":
        user_notes = Notes.objects.filter(owner = request.user).order_by("-importance")
    elif sort == "shared":
        user_notes = Notes.objects.filter(owner = request.user, shared_to = not None)
    else:
        user_notes = Notes.objects.filter(owner = request.user)
    if not note_id:
        try:
            note_id = user_notes[0].id
        except:
            pass
    return render_to_response('notes_menu.html', {'notes': user_notes, 
                                                  'note_id': note_id})
@login_required
@user_passes_test(user_with_email, login_url="/add_email/")
def notes_list(request, note_id=None):
    """
        Return notes list for current user, without a sorting.
    """
    assert request.method == 'GET'
    user_notes = Notes.objects.filter(owner = request.user)
    if not note_id:
        try:
            note_id = user_notes[0].id
        except:
            pass
    return render_to_response('notes_list.html', {'note_id': note_id})

@login_required
@user_passes_test(user_with_email, login_url="/add_email/")
def notes_lists(request, note_id=None):
    """
        Show page with different sortings.
    """
    return render_to_response('notes_lists.html', {})

@login_required
@user_passes_test(user_with_email, login_url="/add_email/")
def save_note(request, note_id=None):
    assert request.method == 'POST' 
    form = NoteForm(request.POST)
    if form.is_valid():
        clean_data = form.cleaned_data
        if note_id:
            note = Notes.objects.get(owner = request.user, id = note_id)
            note.text = clean_data['text']
            note.title = clean_data['title']
            note.importance = clean_data['importance']
            note.save()
        else:
            note = Notes(title = clean_data['title'], text = clean_data['text'], owner = request.user, importance = clean_data['importance'])
            note.save()
            note_id = str(note.id)
        return HttpResponseRedirect('/note_content/' + note_id)

@login_required
@user_passes_test(user_with_email, login_url="/add_email/")
def note_content(request, note_id=None):
    if note_id:
        try:
            note = Notes.objects.get(owner = request.user, id = note_id)
        except:
            raise Http404
    return render_to_response('note_template.html', {'note_text': note.text, 'note_id': note_id, 'importance': note.importance})

@login_required
@user_passes_test(user_with_email, login_url="/add_email/")
def delete_note(request, note_id=0):
    try:
        note = Notes.objects.get(owner = request.user, id = note_id)
        note.delete()
    except:
        pass
    return HttpResponseRedirect('/notes_list/')

notes/templates/notes/add_email.html
{% extends "base.html" %}

{% block title %}Registration{% endblock %}

{% block content %}
<form id="save_note_button" action="" method="post">{% csrf_token %}
    <div class="row-fluid">
        <div class="span12">
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
        </div>
    </div>
    <div class="row-fluid">
        <div class="span1 offset5">
            <table>
                <tr>
                    <td>Please, add email:</td>
                </tr>
                <tr>
                    <td>{{ form.email}}</td>
                </tr>
                <tr>
                    <td><input type="submit" class="btn" value="Confirm"></td>
                </tr>
                <tr>
                    <td>{{form.email.errors}}</td>
                </tr>
            </table>
        </div>
    </div>
</form>
{% endblock %}

notes/templates/notes/base.html
<!DOCTYPE html>   
<html lang="ru">  
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="/static/bootstrap/css/bootstrap.css" rel="stylesheet" media="screen">

    <link href="/static/bootstrap-wysiwyg/external/google-code-prettify/prettify.css" rel="stylesheet">
    <link href="/static/bootstrap-wysiwyg/static/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link href="/static/bootstrap-wysiwyg/static/bootstrap-responsive.min.css" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/3.0.2/css/font-awesome.css" rel="stylesheet">
    <script src="/static/bootstrap-wysiwyg/static/jquery.min.js"></script>
    <script src="/static/bootstrap-wysiwyg/external/jquery.hotkeys.js"></script>
    <script src="/static/bootstrap-wysiwyg/static/bootstrap.min.js"></script>
    <script src="/static/bootstrap-wysiwyg/external/google-code-prettify/prettify.js"></script>
    <link href="/static/bootstrap-wysiwyg/index.css" rel="stylesheet">
    <script src="/static/bootstrap-wysiwyg/bootstrap-wysiwyg.js"></script>
    <link href="/static/css/main.css" rel="stylesheet" type="text/css">

    <script type="text/javascript" src="/static/js/jquery.autocomplete.js"></script>
    <script type="text/javascript" src="/static/js/scripts.js"></script>

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <div class="brand"><a class="main_border" href="{% url main%}" class="">Qolt's</a></div>
            <ul class="nav">
                <li><h1><a class="main_border" href="{% url main%}" class="">NOTES</a></h1></li>
            </ul>
        </div>
    </div>
</div>

<div class="row main_page_row">
</div>

    {% block content %}{% endblock %}
    {% block footer %}
        <hr>
    {% endblock %}
</body>
</html>

notes/templates/notes/edit_note.html
<div>
    <form id="save_note_button" action="{% url save_note %}{{note_id}}" method="post">{% csrf_token %}
        <input type="submit" class="btn note_button save_note_btn" value="Save">
        <div class="hero-unit">
            <div class="row-fluid note_content">
                <div class="row-fluid">
                    <div class="span1 note_content">
                        <label for="id_title">Title:</label>
                    </div>
                    <div class="span6 note_content">
                        {{form.title}}
                    </div>
                    <div class="span5 note_content">
                        {{form.importance}}
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span4 note_content">
                        <label for="id_shared_to">Share this note with:</label>
                    </div>
                    <div class="span3 note_content">
                        {{form.shared_to}}
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        {{form.text}}
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        {% include "wysiwyg_toolbar.html" %}
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12">
                        <div id="editor">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

notes/templates/notes/index.html
{% extends "base.html" %}

{% block title %}Qolt's Notes{% endblock %}

{% block content %}
<div class="container">
    <div class="row main_page_row">
    </div>
    <div class="row main_page_row ">
    </div>
<div class="row main_page_row" >
    <div class="span8 offset2">
        <h3><p>You are logged as {{user}}.</p></h3>
        {%  if user != "Anonymous" %}
           <p><a href="{% url logout %}" class="">Logout</a></p>
            <p><a href="{% url notes_list%}" class="">My notes</a></p>
        {%else%}
    </div>
</div>
<div class="row main_page_row">
    <div class="span2 offset1">
        <a href="{% url socialauth_begin 'google-oauth2' %}">Enter with Google</a>
    </div>
    <div class="span2">
        <a href="{% url socialauth_begin 'yandex' %}">Enter with Yandex</a>
    </div>
    <div class="span2">
        <a href="{% url socialauth_begin 'evernote' %}">Enter with Evernote</a>
    </div>
    <div class="span2">
        <a href="{% url socialauth_begin 'vk-oauth' %}">Enter with VK</a>
    </div>
    <div class="span2">
        <a href="{% url socialauth_begin 'twitter' %}">Enter with Twitter</a>
    </div>
</div>
        {%endif%}
    </div>
</div>

</div>
{% endblock %}

notes/templates/notes/login.html
{% extends "base.html" %}

{% block title %}The current time{% endblock %}

{% block content %}
<p style="margin: 0.4em;">
    <a href="{% url socialauth_begin 'google-oauth2' %}">Enter with Google</a>
</p>
<p style="margin: 0.4em;">
    <a href="{% url socialauth_begin 'yandex' %}">Enter with Yandex</a>
</p>
<p style="margin: 0.4em;">
    <a href="{% url socialauth_begin 'evernote' %}">Enter with Evernote</a>
</p>
<p style="margin: 0.4em;">
    <a href="{% url socialauth_begin 'vk-oauth' %}">Enter with VK</a>
</p>
<p style="margin: 0.4em;">
    <a href="{% url socialauth_begin 'twitter' %}">Enter with Twitter</a>
</p>
{% endblock %}

notes/templates/notes/note_template.html
<div class="btn-group">
    <button type="button" id="edit_note_btn" class="btn note_button">Edit note</button>
    <a href="{%url delete_note%}{{note_id}}">
        <button type="button" id="edit_note_btn" class="btn note_button">Delete note</button>
    </a>
</div>
<div class="hero-unit" id="{{note_id}}">
    <div class="row-fluid">
        <div class="span1">
            <div align="right" class="importance_label" rel="note_edit_tooltip" title="Priority">
                {% if importance == 'Very High' %}
                    <span class="label label-important">{{importance}}</span>
                {%endif%}
                {% if importance == 'High' %}
                    <span class="label label-warning">{{importance}}</span>
                {%endif%}
                {% if importance == 'Normal' %}
                    <span class="label label-success">{{importance}}</span>
                {%endif%}
                {% if importance == 'Low' %}
                    <span class="label label-info">{{importance}}</span>
                {%endif%}
            </div>
        </div>
        <div class="span12">
            <div rel="note_edit_tooltip" title="Double click to edit note">
                {% autoescape off %}{{note_text }}{% endautoescape %}
            </div>
        </div>
    </div>
</div>

notes/templates/notes/notes_list.html
{% extends "base.html" %}

{% block title %}Notes list{% endblock %}

{% block content %}

<script>

function auto_compl(obj) {
    $(obj).autocomplete({
        serviceUrl: '{% url email_auto_compl %}', // Страница для обработки запросов автозаполнения
        minChars: 2, // Минимальная длина запроса для срабатывания автозаполнения
        delimiter: /(,|;)\s*/, // Разделитель для нескольких запросов, символ или регулярное выражение
        maxHeight: 400, // Максимальная высота списка подсказок, в пикселях
        width: 300, // Ширина списка
        zIndex: 9999, // z-index списка
        deferRequestBy: 300, // Задержка запроса (мсек), на случай, если мы не хотим слать миллион запросов, пока пользователь печатает. Я обычно ставлю 300.
        onSelect: function(data, value){ } // Callback функция, срабатывающая на выбор одного из предложенных вариантов,
    });
};

$(function() {

    $("#notes_menu").load("{% url notes_menu %}", function(){
        $("#li_{{note_id}}").addClass("active");     // add active class to the first note in list
    });
    {% if note_id %}
        $("div.span6").load("{% url note_content%}{{note_id}}/ajax"); // load first note
    {% endif %}

    function load_note_content(event){ // load note content
        $("div.span6").bind('dblclick', edit_note);
        var url = $(this).attr("href");
        $("div.span6").load(url + '/ajax', call_wysiwyg);
        history.pushState({id: 'NOTE_ID'}, '', url); 
        add_active_class($(this).parent("li"));
        event.preventDefault();
    };
    $('body').on('click','#notes_list_ul a', load_note_content);

    function add_active_class(element){     // add active class to notes list
        $("li.notes_list_li").removeClass("active");
        element.addClass("active");
    };

    function create_note() {   //create note function.
        var url = $(this).parent("a").attr("href");
        $("div.span6").load(url, call_wysiwyg);
        $("div.span6").unbind('dblclick');
        return false;
    };
    $('body').on('click','#create_note_btn', create_note);

    function call_wysiwyg_with_content() {
        call_wysiwyg();
        $('#editor').html($('#id_text').val());
    };

    function edit_note (){                       //edit note function. Calling edit form.
        var note_id = $("div.hero-unit").attr("id");
        $("div.span6").load("{% url edit_note%}" + note_id, call_wysiwyg_with_content);
        $("div.span6").unbind('dblclick');
    };
    $('body').on('click','#edit_note_btn', edit_note);

    $(".note_text_area").dblclick(edit_note);    // calling edit_note function

    $('body').tooltip({                          // show tooltip function
        selector: "[rel=note_edit_tooltip]", 
        placement: "left", 
    });
    
    function call_wysiwyg() {
        initToolbarBootstrapBindings();  
        $('#editor').wysiwyg({ fileUploadError: showErrorAlert} );
        window.prettyPrint && prettyPrint();
        auto_compl("#id_shared_to");
    };

    function save_note() {
         var r = $('#editor').html();
         $("#id_text").val(r);
    };
    $('body').on('click','.save_note_btn', save_note);

});
</script>
<div class="container-fluid ">
  <div class="row-fluid">
    <div class="span4 offset1">
        <a href="{% url edit_note%}">
            <button type="button" id="create_note_btn" class="btn note_button">Create note</button>
        </a>
        <div id="notes_menu">
        </div>
      <!--Sidebar content-->
    </div>
    <div class="span6 note_text_area">
      <!--Body content--> 
    </div>
  </div>
</div>
{% endblock %}

notes/templates/notes/notes_lists.html
{% extends "base.html" %}

{% block title %}Notes list{% endblock %}

{% block content %}

<script>
$(function() {
    $("#list_by_date").load("{% url notes_menu%}date");
    $("#list_by_priority").load("{% url notes_menu%}importance");
    $("#shared_list").load("{% url notes_menu%}shared");
});
</script>

<div class="container-fluid ">
  <div class="row-fluid">
    <div id="list_by_date" class="span4">
      <!--Sidebar content-->
    </div>
    <div id="list_by_priority" class="span4 verticalLine">
      <!--Body content--> 
    </div>
    <div id="shared_list" class="span4">
      <!--Body content--> 
    </div>
  </div>
</div>
{% endblock %}

notes/templates/notes/notes_menu.html
<ul id="notes_list_ul" class="nav nav-pills nav-stacked">  
    {% for note in notes %} 
    <li class="notes_list_li" id="li_{{note.id}}"><a href="{% url note_content%}{{note.id}}">{{ note.title }}</a></li>  
    {% endfor %}
</ul>  

notes/templates/notes/wysiwyg_toolbar.html
    <div class="btn-toolbar" data-role="editor-toolbar" data-target="#editor">
      <div class="btn-group">
        <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font"><i class="icon-font"></i><b class="caret"></b></a>
          <ul class="dropdown-menu">
          </ul>
        </div>
      <div class="btn-group">
        <a class="btn dropdown-toggle" data-toggle="dropdown" title="Font Size"><i class="icon-text-height"></i>&nbsp;<b class="caret"></b></a>
          <ul class="dropdown-menu">
          <li><a data-edit="fontSize 5"><font size="5">Huge</font></a></li>
          <li><a data-edit="fontSize 3"><font size="3">Normal</font></a></li>
          <li><a data-edit="fontSize 1"><font size="1">Small</font></a></li>
          </ul>
      </div>
      <div class="btn-group">
        <a class="btn" data-edit="bold" title="Bold (Ctrl/Cmd+B)"><i class="icon-bold"></i></a>
        <a class="btn" data-edit="italic" title="Italic (Ctrl/Cmd+I)"><i class="icon-italic"></i></a>
        <a class="btn" data-edit="strikethrough" title="Strikethrough"><i class="icon-strikethrough"></i></a>
        <a class="btn" data-edit="underline" title="Underline (Ctrl/Cmd+U)"><i class="icon-underline"></i></a>
      </div>
      <div class="btn-group">
        <a class="btn" data-edit="insertunorderedlist" title="Bullet list"><i class="icon-list-ul"></i></a>
        <a class="btn" data-edit="insertorderedlist" title="Number list"><i class="icon-list-ol"></i></a>
        <a class="btn" data-edit="outdent" title="Reduce indent (Shift+Tab)"><i class="icon-indent-left"></i></a>
        <a class="btn" data-edit="indent" title="Indent (Tab)"><i class="icon-indent-right"></i></a>
      </div>
      <div class="btn-group">
        <a class="btn" data-edit="justifyleft" title="Align Left (Ctrl/Cmd+L)"><i class="icon-align-left"></i></a>
        <a class="btn" data-edit="justifycenter" title="Center (Ctrl/Cmd+E)"><i class="icon-align-center"></i></a>
        <a class="btn" data-edit="justifyright" title="Align Right (Ctrl/Cmd+R)"><i class="icon-align-right"></i></a>
        <a class="btn" data-edit="justifyfull" title="Justify (Ctrl/Cmd+J)"><i class="icon-align-justify"></i></a>
      </div>
      <div class="btn-group">
          <a class="btn dropdown-toggle" data-toggle="dropdown" title="Hyperlink"><i class="icon-link"></i></a>
            <div class="dropdown-menu input-append">
                <input class="span2" placeholder="URL" type="text" style="width: 200px" data-edit="createLink"/>
                <button class="btn" type="button">Add</button>
        </div>
        <a class="btn" data-edit="unlink" title="Remove Hyperlink"><i class="icon-cut"></i></a>

      </div>
      
      <div class="btn-group">
        <a class="btn" title="Insert picture (or just drag & drop)" id="pictureBtn"><i class="icon-picture"></i></a>
        <input type="file" data-role="magic-overlay" data-target="#pictureBtn" data-edit="insertImage" />
      </div>
      <div class="btn-group">
        <a class="btn" data-edit="undo" title="Undo (Ctrl/Cmd+Z)"><i class="icon-undo"></i></a>
        <a class="btn" data-edit="redo" title="Redo (Ctrl/Cmd+Y)"><i class="icon-repeat"></i></a>
      </div>
    </div>